stages:
  - build
  - deploy

default:
  image: node:lts-alpine3.17
  # Cache modules in between jobs
  cache: &global_cache
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
      - node_modules/
    policy: pull

install-dependencies:
  stage: .pre
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull-push
  script:
    - apk add --no-cache libc6-compat
    - yarn install --cache-folder .yarn-cache --frozen-lockfile --prefer-offline

build-artifacts:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  script:
    - yarn prisma generate
    - yarn build
    - yarn install --cache-folder .yarn-cache --ignore-scripts --prefer-offline --production
  artifacts:
    paths:
      - dist/
      - node_modules/
      - prisma/
      - package.json

push-image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  cache: []
  script:
    - echo "Building Docker image..."
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - echo -e "*\n!dist/\n!node_modules/" > .dockerignore
    - >-
      /kaniko/executor
      --cache=true --cache-copy-layers=true --cache-ttl=24h
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.cicd"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
