stages:
  - build
  - deploy

default:
  image: node:lts-alpine3.17
  # Cache modules in between jobs
  cache: &global_cache
    key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
      - node_modules/
    policy: pull

install-dependencies:
  stage: .pre
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull-push
  script:
    - apk add --no-cache libc6-compat
    - yarn install --cache-folder .yarn-cache --frozen-lockfile --prefer-offline

build-artifacts:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  script:
    - yarn build
    - yarn install --cache-folder .yarn-cache --ignore-scripts --prefer-offline --production
  artifacts:
    paths:
      - dist/
      - node_modules/
      - prisma/
      - package.json

deploy:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  cache: {}
  script:
    - rm -rf *.*
    - cp $ENV_FILE .env
    - wget -q -O build.zip "${BUILD_ARTIFACTS_URL}"
    - unzip -q build.zip
    - node dist/index
