export const houseKeysMap = new Map<string, string>([
    ["link", "link"],
    ["title", "title"],
    ["rentAmount", "rentAmount"],
    //["Categoria", "category"],
    //["Tipo", "type"],
    ["Condomínio", "condominiumFee"],
    ["IPTU", "taxAmount"],
    ["Área útil", "area"],
    ["Quartos", "bedrooms"],
    ["Banheiros", "bathrooms"],
    ["Vagas na garagem", "garages"],
    ["cep", "postalCode"],
    ["Município", "city"],
    ["Bairro", "neighborhood"],
    ["Logradouro", "address"],
  ]);